## First function defines 'subfuntions' to 'read' and 'write' data 
## using an square matrix as argument. Second functions 'decides' if
## needs to do computation or reading operations according the
## information generated by first function.

## Write a short comment describing this function:
## Initially makeCacheMatrix creates an empty matrix, then it defines
## four functions to "write" and "read" the information in x and s
## variables, in "set" kind functions, the values assigned are on an
## superior environment, so they can be used by the CacheSolve funtion.

makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  set <- function(y) {
    x <<- y
    i <<- NULL
  }
  get <- function() x
  setinverse <- function(inverse) i <<- inverse
  getinverse <- function() i
  list(set = set,
       get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}

## Write a short comment describing this function
## cacheSolve function must has as argument makeCacheMatrix
## function, so it can "read" within in if the inverse matrix
## has been calculated already (looking for Nan elements in
## the 'getsolve' data). If the data exists, then there is not
## computation and the data is returned; in the other hand
## the function computes the inverse of the matrix 'stored'
## by 'get' function

cacheSolve <- function(x, ...) {
  i <- x$getinverse()
  if (!is.null(i)) {
    message("getting cached data")
    return(i)
  }
  data <- x$get()
  i <- solve(data, ...)
  x$setinverse(i)
  i
}

##FunctionCalled
B <- matrix(c(1,2,3,4),2,2)
B1 <- makeCacheMatrix(B)

##Returns computed value
cacheSolve(B1) 

##Returns cache value
cacheSolve(B1)
